core:
  server:
    port: env:PORT|8080
    host: localhost
    https:
      disabled: true
    csrf:
      disabled: false
      insecureCookie: true
    cors:
      disabled: false
      origins:
        - http://localhost:8080
        - https://accounts.google.com
  logger:
    level: env:LOG_LEVEL|INFO
    format: json
  repo:
    sqlite:
      url: env:SQLITE_URL|./db.sqlite
      debug: false
  kv:
    sqlite:
      url: env:KV_SQLITE_URL|./kv.sqlite
  search:
    bluge:
oauth2:
  disabled: false
  jwtSecret: "secret"
  clientId: env:OAUTH2_CLIENT_ID|client-id
  clientSecret: env:OAUTH2_CLIENT_SECRET|secret
  redirectUrl: env:OAUTH2_REDIRECT|https://localhost:8080/oauth2/callback
  scopes:
    - "https://www.googleapis.com/auth/userinfo.email"
  endpoint:
    authUrl: "https://accounts.google.com/o/oauth2/auth"
    tokenUrl: "https://accounts.google.com/o/oauth2/token"
  userInfo:
    url: "https://www.googleapis.com/oauth2/v3/tokeninfo"
    emailPath: "email"
    emailVerifiedPath: "email_verified"
