core:
  server:
    port: env:PORT|8080
    host: localhost
    https:
      disabled: false
      certFile: "../../../cert/cert.pem"
      keyFile: "../../../cert/key.pem"
    csrf:
      disabled: false
      insecureCookie: false
    cors:
      disabled: false
      origins:
        - http://localhost:8080
        - https://accounts.google.com
  logger:
    level: env:LOG_LEVEL|INFO
    format: json
  repo:
    pg:
      dsn: env:PG_DSN|postgres://myuser:mypassword@localhost:5432/backline?sslmode=disable
  kv:
    pg:
      dsn: env:PG_DSN|postgres://myuser:mypassword@localhost:5432/backline?sslmode=disable
  lock:
    pg:
      dsn: env:PG_DSN|postgres://myuser:mypassword@localhost:5432/backline?sslmode=disable
  search:
    elastic:
      addresses:
        - http://localhost:9200
      username: elastic
      password: changeme
      indexName: backline-search
  scanner:
    enableScanEndpoint: true
    enableScanButton: true
    scanBeforeStart: true
locations:
  fs:
    - "/home/user/dev/ent"
  github:
    - owner: backstage
      repo: backstage
      branch: master
      accessToken: env:GITHUB_ACCESS_TOKEN
      depth: 1
      paths:
        - packages/catalog-model/examples
oauth2:
  disabled: false
  jwtSecret: "secret"
  clientId: env:OAUTH2_CLIENT_ID|client-id
  clientSecret: env:OAUTH2_CLIENT_SECRET|secret
  redirectUrl: env:OAUTH2_REDIRECT|http://localhost:8080/oauth2/callback
  scopes:
    - "https://www.googleapis.com/auth/userinfo.email"
  endpoint:
    authUrl: "https://accounts.google.com/o/oauth2/auth"
    tokenUrl: "https://accounts.google.com/o/oauth2/token"
  userInfo:
    url: "https://www.googleapis.com/oauth2/v3/tokeninfo"
    emailPath: "email"
    emailVerifiedPath: "email_verified"
