name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.64

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - id: set-modules
        run: |
          # Get modules with their full path from repo root
          echo "modules=$(go list -m -json | jq -r -s 'map(.Dir) | map(sub("${GITHUB_WORKSPACE}/"; "")) | .[]' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  golangci-lint:
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download dependencies
        working-directory: ${{ matrix.module }}
        run: |
          go mod download
          go mod verify

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.module }}
          args: --config ${{ github.workspace }}/.golangci.yaml ./...